import Head from "next/head";
import { Header } from "src/components/Header";
import { Array } from "src/components/Array";

export default function Home() {
	return (
		<div className="">
			<Head>
				<title>fifth</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			
		</div>
	);
}
