import Head from "next/head";
import Image from "next/image";
import { Header } from "src/components/Header";

export default function Home() {
	// const photos = [
	// 	{
	// 		id: 1,
	// 		photo:"/525-1.jpeg" ,
	// 	},
	// 	{
	// 		id: 2,
	// 		photo:"/525-2.jpeg" ,
	// 	},
	// ]
	// return (
	// 	<ul>
	// 		{photos.map(id,photo => {
	// 			<li>
	// 				<img key={id} src={photo} /> 
	// 			</li>
	// 		})}
	// 	</ul>
	// )

	return (
		<div>
			<Header />
			<Head>
				<title>Third</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="w-auto mt-8 mx-10">
				<div className="  h-10 border-2  leading-10">
					<p className="text-yellow-600 text-4xl">MyCar紹介</p>
				</div>
					<div className=" h-40 border-2  leading-60">

					<Image src="/525-1.jpeg" width={300} height={150} objectFit="contain"/>
					</div>

				<div></div>
			</main>
		</div>
	);
}
