import Head from "next/head";
import { Header } from "src/components/Header";

import Title from "src/components/Title";

const Fourth = () => {
	return (
		<div className="flex justify-center">
			<div className=" container max-w-5xl ">
				<div className="h-screen m-6   border-yellow-800 border-2 p-3 rounded-lg bg-yellow-100">
					<Title title="の感想"/>
					<Header />
					<Head>
						<title>感想</title>
						<meta name="description" content="Generated by create next app" />
						<link rel="icon" href="/favicon.ico" />
					</Head>




				</div>
			</div>
		</div>
	);
};
export default Fourth;
