import Head from "next/head";
import Image from "next/image";
import { useCallback, useEffect, useState } from "react";
import { Header } from "src/components/Header";

const Index = () => {
	const [items, setItems] = useState([]);
	const getItems = useCallback(() => {
		const PHOTOS = [
			{ id: "1", img: "/1.jpeg" },
			{ id: "2", img: "/2.jpeg" },
		];
		setItems(PHOTOS);
	}, [setItems]);
	useEffect(() => {
		getItems();
	}, [getItems]);

	return (
		<div className="flex justify-center">
			<div className=" container max-w-5xl max-h-full">
				<div className=" m-6   border-yellow-800 border-2 p-3 rounded-lg bg-yellow-100">
					<div className="flex flex-wrap mt-4">
						<p className="font-bold font-Arial  text-red-600 text-6xl  text-left ml-10">
							BMW525-D
						</p>
						<p className="font-bold p-2 text-yellow-900 text-4xl   ml-6">
							の紹介
						</p>
					</div>

					<Header />
					<Head>
						<title>HOME</title>
						<meta name="description" content="Generated by create next app" />
						<link rel="icon" href="/favicon.ico" />
					</Head>
					<main className="w-auto h-screen  mx-10">
						{/* <div className="  h-10  italic">
							<p className=" font-mono text-blue-600 text-4xl">
								駆け抜ける喜び
							</p>
						</div> */}
						<div className="mb-16 mt-8">
							<div className="h-screen mt-4">
								{items.map((item) => {
									return (
										<Image
											key={item.id}
											src={item.img}
											alt="Picture of the author"
											width={700}
											height={400}
										/>
									);
								})}
							</div>
						</div>

			
					</main>
				</div>
			</div>
		</div>
	);
};
export default Index;
