import Head from "next/head";
import Image from "next/image";

import { Header } from "src/components/Header";
import Title from "src/components/Title";

const Index = (props) => {
	return (
		<div className="flex justify-center">
			<div className=" container w-screen max-h-full">
				<div className=" m-6   border-yellow-800 border-2 p-3 rounded-lg bg-yellow-50">
					<Title title="の紹介" />

					<Header />
					<Head>
						<title>HOME</title>
						<meta name="description" content="Generated by create next app" />
						<link rel="icon" href="/favicon.ico" />
					</Head>
					<main className="flex  min-h-full mx-10">
						<div className="mb-16 mt-8">
							<div className="lg:flex relative mt-4">
								<div>
									<div className="mr-10">
										<Image
											className=""
											src={"/1.jpeg"}
											alt="Picture of the author"
											width={700}
											height={400}
										/>
										<span className="italic absolute top-[5px] left-[10px] font-mono text-green-400 text-4xl xl:hover:text-pink-400">
											駆け抜ける喜び
										</span>
									</div>

									<div className="mt-10 mb-10 mr-10">
										<Image
											// className="translate-y-[400px]"
											src={"/2.jpeg"}
											alt="Picture of the author"
											width={700}
											height={400}
										/>
									</div>
								</div>
								<div>
									<div className="">
										<Image
											// className="invisible"
											src={"/3.jpeg"}
											alt="Picture of the author"
											width={700}
											height={400}
										/>
									</div>
									<div className="mt-10">
										<Image
											// className="opacity-0 transition-opacity "
											src={"/4.jpeg"}
											alt="Picture of the author"
											width={700}
											height={400}
										/>
									</div>
								</div>
							</div>
						</div>
					</main>
				</div>
			</div>
		</div>
	);
};
export default Index;
