import Head from "next/head";
import { Header } from "src/components/Header";
import { Array } from "src/components/Array";

export default function Home() {
	return (
		<div>
			<Header />
			<Head>
				<title>Second</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="w-auto mt-8 mx-10">
				<div className="  h-10 border-2  leading-10">
					<p className="text-blue-500 text-4xl">2番目</p>
				</div>
				
			<Array />
			</main>
		</div>
	);
}
