import Head from "next/head";
import { Header } from "src/components/Header";
import { Array3 } from "src/components/third/inPhoto";
import Title from "src/components/Title";

const Third = () => {
	return (
		<div className="flex justify-center">
			<div className=" container max-w-5xl h-screen">
				<div className="m-6   border-yellow-800 border-2 p-3 rounded-lg bg-pink-40">
					<Title title="の内装"/>
					<Header />
					<Head>
						<title>内装</title>
						<meta name="description" content="Generated by create next app" />
						<link rel="icon" href="/favicon.ico" />
					</Head>
					<main className="w-auto mt-8 mx-10">


						<Array3 />
					</main>
				</div>
			</div>
		</div>
	);
};
export default Third;
